### ISSUE TITLE
'Mismatched types' error when building eurochef-cli

### ISSUE THREAD

**Issue by applecuckoo** [eurotools/eurochef#29]
Hi! I was trying to install Eurochef, so I got Rust set up and ran `cargo install --git https://github.com/eurotools/eurochef.git`. I ended up with a `mismatched types` error which I have stored in [this gist](https://gist.github.com/applecuckoo/fe18352dd12baad75c1e84ba509ec5b0) for brevity. From the debug log it seems that these two lines are problematic:
https://github.com/eurotools/eurochef/blob/774c7c5d6e1029523b76a346f5b658fdfde54997/eurochef-edb/src/map.rs#L176
https://github.com/eurotools/eurochef/blob/774c7c5d6e1029523b76a346f5b658fdfde54997/eurochef-edb/src/anim.rs#L49
My guess is that these are simple bug fixes, but I won't send in a PR since I'm not fluent in Rust.

**Comment by applecuckoo** [comment]
Cargo version is 1.74.1 (ecb9851af 2023-10-18). Thanks for the binaries, but I use Linux so that's why I'm building from source.

**Comment by cohaereo** [comment]
Eurochef is meant to be compiled with the nightly rust toolchain. Try using that
```sh
rustup toolchain install nightly
rustup default nightly
```

**Comment by applecuckoo** [comment]
@cohaereo It's still erroring out:
```
error[E0308]: mismatched types
  --> eurochef-edb/src/anim.rs:49:48
   |
49 | ...rgs(&skin_data_ptr, parts_count))]
   |        ^^^^^^^^^^^^^^ expected `(&EXRelPtr, u32)`, found `&EXRelPtr`
   |
   = note:  expected tuple `(&EXRelPtr, u32)`
           found reference `&EXRelPtr`

error[E0308]: mismatched types
   --> eurochef-edb/src/anim.rs:49:43
    |
42  | #[binrw]
    | -------- arguments to this function are incorrect
...
49  |     #[br(parse_with(parse_late_skindata), args(&skin_data_ptr, parts_co...
    |                                           ^^^^ expected a tuple with 1 element, found one with 2 elements
    |
    = note: expected tuple `((&EXRelPtr, u32),)`
               found tuple `((&EXRelPtr, u32), u32)`
help: the return type of this call is `((&EXRelPtr, u32), u32)` due to the type of the argument passed
   --> eurochef-edb/src/anim.rs:42:1
    |
42  | #[binrw]
    | ^^^^^^^^
...
49  |     #[br(parse_with(parse_late_skindata), args(&skin_data_ptr, parts_co...
    |                                           ---- this argument influences the return type of `binrw`
note: function defined here
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/binrw-0.11.2/src/private.rs:107:8
    |
107 | pub fn parse_function_args_type_hint<R, Res, Args, F>(_: F, a: Args) ->...
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: this error originates in the attribute macro `binrw` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> eurochef-edb/src/map.rs:174:51
    |
174 |     #[br(parse_with = parse_trigdata_values, args(trig_flags))]
    |                                                   ^^^^^^^^^^ expected `(u32,)`, found `u32`
    |
    = note: expected tuple `(u32,)`
                found type `u32`
help: use a trailing comma to create a tuple with one element
    |
174 |     #[br(parse_with = parse_trigdata_values, args((trig_flags,)))]
    |                                                   +          ++

error[E0308]: mismatched types
   --> eurochef-edb/src/map.rs:176:49
    |
176 |     #[br(parse_with = parse_trigdata_link, args(trig_flags))]
    |                                                 ^^^^^^^^^^ expected `(u32,)`, found `u32`
    |
    = note: expected tuple `(u32,)`
                found type `u32`
help: use a trailing comma to create a tuple with one element
    |
176 |     #[br(parse_with = parse_trigdata_link, args((trig_flags,)))]
    |                                                 +          ++

For more information about this error, try `rustc --explain E0308`.
   Compiling gltf v1.4.0
error: could not compile `eurochef-edb` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `eurochef-cli v0.1.0 (https://github.com/eurotools/eurochef.git#a2b6d502)`, intermediate artifacts can be found at `/tmp/cargo-installECAMjF`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by cohaereo** [comment]
Problem is I cannot reproduce this error. Applying the fixes rustc is suggesting causes an error on my end.

**Comment by cohaereo** [comment]
Scratch that, I just managed to reproduce it by updating `binrw`. It seems like for some reason cargo pulled in a newer version of binrw (1.11.2) than specified in the project files (1.11.0). This means that the binrw maintainer performed a breaking change on a minor change version, shame on them 😕

Anyway, i'm going to update binrw and fix the issue

**Comment by applecuckoo** [comment]
I had a dig around and found the binrw [changelog](https://github.com/jam1garner/binrw/releases/tag/v0.11.2) for 0.11.2 and there were only two 'bug fixes' mentioned. I'll leave it to you to decide if that qualifies as a bug fix :-)

**Comment by cohaereo** [comment]
@applecuckoo I've pushed the fix, try it now

**Comment by applecuckoo** [comment]
@cohaereo Welp, still doesn't work. Now it spits out 16 different errors! The log is [here](https://gist.github.com/applecuckoo/5a9efd179a373590088001846246da4e).

**Comment by cohaereo** [comment]
Your Rust installation seems to be downloading newer packages than the ones specified in the lock file.

**Comment by cohaereo** [comment]
Either way, I've updated the gltf package and fixed the build errors, try once more

**Comment by applecuckoo** [comment]
All I had to do was add the --locked flag and the build compiled without any errors. It does warn that
`warning: package 'hermit-abi v0.3.1' in Cargo.lock is yanked in registry 'crates-io', consider running without --locked`. Should I be concerned?

**Comment by cohaereo** [comment]
Shouldn't be an issue if it compiled

**Comment by applecuckoo** [comment]
Alright then, I'll close the issue.
